### ISSUE TITLE
Port forwarding in vsonline web client doesn't play nice with kestrel over https

### ISSUE THREAD

**Issue by nathansoz** [MicrosoftDocs/vscodespaces#123]
I'm using a dotnet core web app that accepts connections over https only. When I click on the forwarded port and get the [redacted].app.online.visualstudio.com link, I get this error in my application:

```
dbug: Microsoft.AspNetCore.Server.Kestrel.Https.Internal.HttpsConnectionAdapter[1]
      Failed to authenticate HTTPS connection.
System.IO.IOException: The handshake failed due to an unexpected packet format.
   at System.Net.Security.SslState.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.PartialFrameCallback(AsyncProtocolRequest asyncRequest)
--- End of stack trace from previous location where exception was thrown ---
   at System.Net.Security.SslState.ThrowIfExceptional()
   at System.Net.Security.SslState.InternalEndProcessAuthentication(LazyAsyncResult lazyResult)
   at System.Net.Security.SslState.EndProcessAuthentication(IAsyncResult result)
   at System.Net.Security.SslStream.EndAuthenticateAsServer(IAsyncResult asyncResult)
   at System.Net.Security.SslStream.<>c.<AuthenticateAsServerAsync>b__51_1(IAsyncResult iar)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
```

and this error on the webpage:

```
[redacted].app.online.visualstudio.com took too long to respond.
HTTP ERROR 504
```

This whole setup works fine if I connect from VS Code. I'm *assuming* that there is a certificate problem here that isn't easy to solve (http proxy with the online editor and a more direct port forwarding mechanism with vs code?), but I wanted to raise this issue to put it on your radar. If you don't plan on solving it, I'd document that the online editor doesn't port forward apps over https.

**Comment by wpitallo** [comment]
Any updates on this?

**Comment by fara-nak** [comment]
thanks for contacting us and sorry for the delay, We are improving our PortForwarding service in general to resolve many of the existing issues, we will update this thread as soon as releasing the new PF service.

**Comment by lostintangent** [comment]
@plisy Now that the new port forwarding service was deployed to VSCS, can we resolve this as fixed?

**Comment by plisy** [comment]
Yes this can be closed now.

**Comment by wpitallo** [comment]
Hi @lostintangent, @plisy any idea how I could get access to github codespaces?

**Comment by legomushroom** [comment]
@wpitallo you can signup for the beta here: https://github.com/features/codespaces/signup
