### ISSUE TITLE
Register Local Environment Failure: Your sign in token has expired.

### ISSUE THREAD

**Issue by DragonMastery** [MicrosoftDocs/vscodespaces#271]
Register Local Environment Failure: vso share failed: Microsoft.Cascade.Rpc.RemoteException: Your sign in token has expired. Please sign out and in again to refresh it. If the issue persists, please log a bug. **(I tried signing out and signing back in, reinstalling, multiple attempt, nothing fixed it)**
   at Microsoft.Cascade.Rpc.ResponseError.ThrowAsException() in E:\A\_work\336\s\src\Rpc\Messages.cs:line 624
   at Microsoft.Cascade.Rpc.RpcProxy.SendRequestAsync(RequestMessage request, CancellationToken cancellationToken, IProgress`1 progress) in E:\A\_work\336\s\src\Rpc\RpcProxy.cs:line 243
   at Microsoft.Cascade.Rpc.RpcProxy.InvokeWithResultAsync[TResult](String methodName, Object[] arguments, CancellationToken cancellationToken) in E:\A\_work\336\s\src\Rpc\RpcProxy.cs:line 198
   at Microsoft.CloudEnvironments.CLI.Managers.WorkspaceManager.ShareAsync(ICascadeClient client, String path, Boolean allowAnonymousGuests, String workspaceId) in E:\A\_work\336\s\src\VSOnline\CLI\Managers\WorkspaceManager.cs:line 116
   at Microsoft.CloudEnvironments.CLI.Managers.WorkspaceManager.ShareAsync(String path, Boolean allowAnonymousGuests, String workspaceId) in E:\A\_work\336\s\src\VSOnline\CLI\Managers\WorkspaceManager.cs:line 77
   at Microsoft.CloudEnvironments.CLI.Commands.ShareWorkspaceCliCommandStrategy.ShareAsync(String path, Boolean allowAnonymousGuests, String workspaceRegexToken, String workspaceId) in E:\A\_work\336\s\src\VSOnline\CLI\Commands\ShareWorkspaceCliCommandStrategy.cs:line 48
   at Microsoft.CloudEnvironments.CLI.Commands.ShareWorkspaceCliCommandStrategy.<>c__DisplayClass4_1.<<Register>b__1>d.MoveNext() in E:\A\_work\336\s\src\VSOnline\CLI\Commands\ShareWorkspaceCliCommandStrategy.cs:line 40
 (88390ms)

**Comment by DragonMastery** [comment]
I had to clear the saved credentials from my windows credential manager and that fixed it. I think it was trying to access the wrong directory in azure.

**Comment by TimPorterDT** [comment]
^^ Clearing the saved credentials worked for me too.

**Comment by DragonMastery** [comment]
FYI this is consistently happening, so i am constantly having to clear out credentials. I am not signing in more than once...

**Comment by taiyosogawa** [comment]
@DragonMastery, I'm very sorry for the horrendously overdue reply. Thank you for reporting the credential issue. We are currently working on this issue and plan on releasing the fix within the next two weeks.

**Comment by taiyosogawa** [comment]
Hi - apologies for the late update: The fix to resolve this should be going out next week.
