### ISSUE TITLE
Register multiple self-hosted environment, same Windows VM

### ISSUE THREAD

**Issue by JAgostoni** [MicrosoftDocs/vscodespaces#384]
VS Code extension: 1.0.1889
Windows Server 2019

**Goal:**
We are attempting to share a Windows 10 VM to run multiple self-hosted environments.  Each user is logged into their own user profile and also their own Azure login.  

**Issue:**
We can only register and/or launch one self-hosted environment at at time. Otherwise, we get see this (or similar) error in the log files:

```Command [Restore Self-hosted Environment]: Restore Self-hosted Environment Failure: vso login failed: System.UnauthorizedAccessException: Access to the path is denied.```

Full error stack below.

**Repro**

1. User 1 logs into VM, launches VS Code, signs into Azure, registers self-hosted, verifies from online.visualstudio.com
2. User 2 logs into VM, launched VS Code, signs into Azure, attempts to register, gets error
3. User 1 completely logs OUT of VM
4. User 2 attempts to register self-hosted env. again, this time with success
5. User 1 logs into VM, attempts to RESTORE environment, gets error

Full error stack:

```
[2020-04-06 19:24:33.251 Command:l I] Decorator finishing: a. Duration: 16ms (1 + 15)
[2020-04-06 19:24:38.118 Command:l I] Decorator finishing: l. Duration: 4867ms (0 + 4867)
[2020-04-06 19:26:05.321 Command:l I] Decorator starting: l
[2020-04-06 19:26:05.321 Command:l I] Decorator starting: a
[2020-04-06 19:26:06.949 Command:l E] Command [Restore Self-hosted Environment]: Restore Self-hosted Environment Failure: vso login failed: System.UnauthorizedAccessException: Access to the path is denied.
   at System.IO.Pipes.NamedPipeClientStream.TryConnect(Int32 timeout, CancellationToken cancellationToken)
   at System.IO.Pipes.NamedPipeClientStream.ConnectInternal(Int32 timeout, CancellationToken cancellationToken, Int32 startTime)
   at System.IO.Pipes.NamedPipeClientStream.<>c__DisplayClass20_0.<ConnectAsync>b__0()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Cascade.Rpc.PipeRpcClient.ConnectAsync(CancellationToken cancellationToken) in E:\A\_work\122\s\src\Rpc\PipeRpcClient.cs:line 34
   at Microsoft.Cascade.Client.CascadeClient.CreateWithTimeoutAsync(IRpcClient rpcClient, TimeSpan timeout, TraceSource trace, CancellationToken cancellationToken) in E:\A\_work\122\s\src\Client\CascadeClient.cs:line 141
   at Microsoft.VisualStudio.VSOnline.Core.CascadeFactory.CreateClientAsync(String pipeName, Boolean autoStart) in E:\A\_work\122\s\src\VSOnline\Core\CascadeFactory.cs:line 47
   at Microsoft.VisualStudio.VSOnline.Core.Managers.AuthenticationManager.LoginExchangeAsync(String aadToken, String pipeName, String serviceUri) in E:\A\_work\122\s\src\VSOnline\Core\Managers\AuthenticationManager.cs:line 100
   at Microsoft.CloudEnvironments.CLI.Commands.LoginAuthenticationCliCommandStrategy.LoginExchangeAsync(String aadToken, String pipeName, String serviceUri) in E:\A\_work\122\s\src\VSOnline\CLI\Commands\LoginAuthenticationCliCommandStrategy.cs:line 69
   at Microsoft.CloudEnvironments.CLI.Commands.LoginAuthenticationCliCommandStrategy.<>c__DisplayClass4_2.<<Register>b__3>d.MoveNext() in E:\A\_work\122\s\src\VSOnline\CLI\Commands\LoginAuthenticationCliCommandStrategy.cs:line 54
 (1628ms)
[2020-04-06 19:26:06.949 Command:l I] Decorator finishing: a. Duration: 3ms (0 + 3)
[2020-04-06 19:26:09.674 Command:l I] Decorator finishing: l. Duration: 2725ms (0 + 2725)```

**Comment by jkeech** [comment]
@taiyosogawa, it looks like one user’s agent is trying to access the named pipe of the other, which would hit the permissions issue. How do self-hosted agents from multiple user accounts keep each other’s pipes separate?

**Comment by taiyosogawa** [comment]
@JAgostoni, thanks for reporting this issue with very detailed information. @jkeech, yes, I believe you are right about a conflicting pipe name. We'll have to make some changes to avoid that conflict, which we can track here.

**Comment by taiyosogawa** [comment]
We've got an update for this, which should start deploying next week. I'll post again when it's out.

**Comment by 2percentsilk** [comment]
Given the inactivity on this issue and the impending [retirement of self-hosted machines](https://docs.microsoft.com/en-us/visualstudio/codespaces/resources/consolidation-faq#self-hosted-codespaces) on November 20, 2020 as part of the [consolidation of VS Codespaces into GitHub](aka.ms/vscs-transition), I'm going to go ahead and close this issue.

If you have any thoughts/feedback on self-hosted Codespaces support in GitHub, please let us know by commenting on this [issue](https://github.community/t/self-hosted-codespaces/131361/19).
