### ISSUE TITLE
"Failed to start VS Code Remote server" when trying to connect to MacBook from Windows

### ISSUE THREAD

**Issue by DanTup** [MicrosoftDocs/vscodespaces#405]
I'm trying to connect VS Code on Windows to VS Code on my MacBook. I'm sure this worked in the past, but today (with latest stable versions of everything), I'm hitting this error.

What I did:

- Opened VS Code on MacBook
- Ran "VS Online: Register Self-Host Environment"
- Selected to run as a process
- Gave a name, selected a folder

- Opened VS Code on Windows PC
- Ran "VS Online: Connect to Environment"
- See "Failed to start VS Code Remote server." in VS Code notification and dev tools

![Untitled](https://user-images.githubusercontent.com/1078012/79253412-15339280-7e7b-11ea-889b-1be169b0d264.png)

I'm not sure how to debug - the error isn't very specific and I don't know if there's a way to get any logs from the MacBook (there's nothing relevant in its dev tools).

**Comment by taiyosogawa** [comment]
Hi @DanTup, thanks for trying out self-hosted environments and reporting the detailed issue.

Based on your notes, we can tell a couple things:
1) It looks like the agent on the host MacBook did run successfully for a bit (otherwise the environment would be in a "provisioning" or "failed" state).
2) Since the agent on the host machine was run as a process, it will stop functioning if it dies for any reason. However, I don't think this is what happened based on the error message I see in the screenshot.

I've got a few more questions to help diagnose. I understand it might be too late to capture some of it, so don't worry:
1) How long was it between registering the environment and connecting to it? It sounds like you tested it right away - is that right?
2) On the host machine, do you see a `vso` or `vsls-agent` process running? Do you see a node process running out of the `~/.vscode-remote` directory?
3) The logs are located under `$TMPDIR/VSFeedbackVSRTCLogs`. Try: `grep "Failed to find port in output" $TMPDIR/VSFeedbackVSRTCLogs/*` (or seeing if there's anything else that looks suspicious).

**Comment by DanTup** [comment]
Sorry for the delay in responding!

1. It was within a few minutes. I started it on the MacBook, then moved to the PC and tried to connect (it showed up in the list of environments and I clicked there).
2. I see this agent process:

    ```
    danny@Dannys-MBP ~ % pgrep -lf vsls                
    6856 /Users/danny/.vsonline/cli/VSOAgent_osx_3632209/vsls-agent --pipe VSLS-SH --service https://prod.liveshare.vsengsaas.visualstudio.com/api/v1.2/ --rpcFirstSessionTimeout 120000 --autoexit --verbosity All --agentExtensionPath /Users/danny/.vsonline/cli/VSOAgent_osx_3632209/AgentExtensions
    ```
    but as far as I can tell, no node process running.
3. Logs:
    From Windows (client):
    - [20200421_104531_15874659311620_VSCode.log](https://github.com/MicrosoftDocs/vsonline/files/4509458/20200421_104531_15874659311620_VSCode.log)
    - [20200421_104618_15874659781450_VSCode.log](https://github.com/MicrosoftDocs/vsonline/files/4509459/20200421_104618_15874659781450_VSCode.log)
    - [20200421_104624_15874659848720_VSCode.log](https://github.com/MicrosoftDocs/vsonline/files/4509460/20200421_104624_15874659848720_VSCode.log)
    From Mac (host):
    - TODO: Edit in from Mac

**Comment by DanTup** [comment]
I'm not sure if attaching the macOS logs in full is wise (there are things that might be keys in there), but there are a lot of errors in there like this:

```
[2020-04-21 10:39:50.012 Agent.Workspace I] Starting script (0): bash "/Users/danny/.vsonline/cli/VSOAgent_osx_3632209/AgentExtensions/vscode-install.sh" server-darwin-web 2aae1f26c7289XXXXXXXXXXXXXXXX435a154b13 a779b196-a951-XXXX-96fb-ee8f471e3432 stable "--install-extension ms-vsonline.vsonline --install-extension GitHub.vscode-pull-request-github --install-extension ms-vsliveshare.vsliveshare --install-extension visualstudioexptteam.vscodeintellicode --force" True
[2020-04-21 10:39:50.014 Agent.Workspace E] Failed to run VS Code Remote setup script: System.ComponentModel.Win32Exception (2): No such file or directory
   at System.Diagnostics.Process.ForkAndExecProcess(String filename, String[] argv, String[] envp, String cwd, Boolean redirectStdin, Boolean redirectStdout, Boolean redirectStderr, Boolean setCredentials, UInt32 userId, UInt32 groupId, UInt32[] groups, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean usesTerminal, Boolean throwOnNoExec)
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at Microsoft.VisualStudio.LiveShare.Agent.VSCodeServerHost.VSCodeServerHostService.RunServerScriptAsync(String arguments, Action`1 outputCallback, Action`1 errorCallback, Dictionary`2 remoteEnv, VSCodeServerOptions options)
   at Microsoft.VisualStudio.LiveShare.Agent.VSCodeServerHost.VSCodeServerHostService.StartRemoteServerAsync(VSCodeServerOptions input, CancellationToken cancellationToken)
[2020-04-21 10:39:50.016 Agent.Workspace E] Exception in IVSCodeServerHostService.startRemoteServer request handler: System.Exception: Failed to start VS Code Remote server.
 ---> System.ComponentModel.Win32Exception (2): No such file or directory
   at System.Diagnostics.Process.ForkAndExecProcess(String filename, String[] argv, String[] envp, String cwd, Boolean redirectStdin, Boolean redirectStdout, Boolean redirectStderr, Boolean setCredentials, UInt32 userId, UInt32 groupId, UInt32[] groups, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean usesTerminal, Boolean throwOnNoExec)
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at Microsoft.VisualStudio.LiveShare.Agent.VSCodeServerHost.VSCodeServerHostService.RunServerScriptAsync(String arguments, Action`1 outputCallback, Action`1 errorCallback, Dictionary`2 remoteEnv, VSCodeServerOptions options)
   at Microsoft.VisualStudio.LiveShare.Agent.VSCodeServerHost.VSCodeServerHostService.StartRemoteServerAsync(VSCodeServerOptions input, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at Microsoft.VisualStudio.LiveShare.Agent.VSCodeServerHost.VSCodeServerHostService.StartRemoteServerAsync(VSCodeServerOptions input, CancellationToken cancellationToken)
   at Microsoft.Cascade.Rpc.RpcDispatcher`1.<>c__DisplayClass24_2.<<CreateDispatchMethod>b__4>d.MoveNext() in E:\A\_work\403\s\src\Rpc\RpcDispatcher.cs:line 310
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Cascade.Rpc.RpcDispatcher`1.HandleRequestAsync(RequestMessage request, IProgress`1 progress, CancellationToken cancellationToken) in E:\A\_work\403\s\src\Rpc\RpcDispatcher.cs:line 102
   at Microsoft.Cascade.Rpc.RpcSession.RequestAsync(IRpcService service, RequestMessage message, CancellationToken cancellation) in E:\A\_work\403\s\src\Rpc\RpcSession.cs:line 702
[2020-04-21 10:39:50.026 Agent.Workspace V] < #5 {Id=5 Error={Code=-32098 Message=Failed to start VS Code Remote server. Data=(StackTrace=System.Exception: Failed to start VS Code Remote server.
 ---> System.ComponentModel.Win32Exception (2): No such file or directory
   at System.Diagnostics.Process.ForkAndExecProcess(String filename, String[] argv, String[] envp, String cwd, Boolean redirectStdin, Boolean redirectStdout, Boolean redirectStderr, Boolean setCredentials, UInt32 userId, UInt32 groupId, UInt32[] groups, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean usesTerminal, Boolean throwOnNoExec)
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at Microsoft.VisualStudio.LiveShare.Agent.VSCodeServerHost.VSCodeServerHostService.RunServerScriptAsync(String arguments, Action`1 outputCallback, Action`1 errorCallback, Dictionary`2 remoteEnv, VSCodeServerOptions options)
   at Microsoft.VisualStudio.LiveShare.Agent.VSCodeServerHost.VSCodeServerHostService.StartRemoteServerAsync(VSCodeServerOptions input, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at Microsoft.VisualStudio.LiveShare.Agent.VSCodeServerHost.VSCodeServerHostService.StartRemoteServerAsync(VSCodeServerOptions input, CancellationToken cancellationToken)
   at Microsoft.Cascade.Rpc.RpcDispatcher`1.<>c__DisplayClass24_2.<<CreateDispatchMethod>b__4>d.MoveNext() in E:\A\_work\403\s\src\Rpc\RpcDispatcher.cs:line 310
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Cascade.Rpc.RpcDispatcher`1.HandleRequestAsync(RequestMessage request, IProgress`1 progress, CancellationToken cancellationToken) in E:\A\_work\403\s\src\Rpc\RpcDispatcher.cs:line 102
   at Microsoft.Cascade.Rpc.RpcSession.RequestAsync(IRpcService service, RequestMessage message, CancellationToken cancellation) in E:\A\_work\403\s\src\Rpc\RpcSession.cs:line 702)}}
[2020-04-21 10:40:00.266 Agent.Ssh V] (9001) Microsoft.Azure.Relay.RelayException: Unable to read data from the transport connection: Connection reset by peer. TrackingId:05879910-XXXX-4151-9743-4aeff92dd5f6_G2_G4, Address:sb://vsls-prod-ins-euw-private-relay.servicebus.windows.net/6bc0dXXXX082804e5e8c0e4fa--5440c919-e5fb-XXXX-9064-32e95ce83fba, Timestamp:04/21/2020 10:40:00
 ---> System.Net.WebSockets.WebSocketException (0x80004005): The remote party closed the WebSocket connection without completing the close handshake.
 ---> System.IO.IOException: Unable to read data from the transport connection: Connection reset by peer.
 ---> System.Net.Sockets.SocketException (54): Connection reset by peer
```

**Comment by DanTup** [comment]
And FWIW, if I try "Open in Browser" on the MacBook that's the host, I see the same behaviour in the browser based VS (it shows the same message failing to connect).

**Comment by DanTup** [comment]
It appears to:

```
danny@Dannys-MBP AgentExtensions % pwd && ls
/Users/danny/.vsonline/cli/VSOAgent_osx_3632209/AgentExtensions
Microsoft.VisualStudio.LiveShare.Agent.EnvironmentService.dll  Microsoft.VisualStudio.VSOnline.Contracts.dll
Microsoft.VisualStudio.LiveShare.Agent.VSCodeServerHost.dll    Microsoft.VisualStudio.VSOnline.Core.dll
Microsoft.VisualStudio.LiveShare.Agent.VSServerHost.dll        vscode-install.sh
Microsoft.VisualStudio.VSOnline.Common.dll                     vsonline-companion.tgz
```

I don't know if it matters, but doesn't seem like it's marked executable?

```
danny@Dannys-MBP AgentExtensions % ls -la ~/.vsonline/cli/VSOAgent_osx_3632209/AgentExtensions/vscode-install.sh
-rw-r--r--  1 danny  staff  6052 21 Apr 11:39 /Users/danny/.vsonline/cli/VSOAgent_osx_3632209/AgentExtensions/vscode-install.sh

danny@Dannys-MBP AgentExtensions % ./vscode-install.sh
zsh: permission denied: ./vscode-install.sh
```

**Comment by taiyosogawa** [comment]
Ah, I see. Great thinking, but it shouldn't need to be marked as executable since it's fed as an argument to bash. I guess the next question is: is bash installed and set in the PATH?

**Comment by DanTup** [comment]
Ah, ok.

Does seem like Bash is here:

```
danny@Dannys-MBP branch_change_repo % which bash
/bin/bash
```

It's a fairly new MacBook Pro and should be fairly stock (I tend not to mess with things too much, so it's easy to reset and start again without doing it all over 😄).

I'm curious about the error though:

```
[2020-04-21 10:39:50.012 Agent.Workspace I] Starting script (0): bash "/Users/danny/.vsonline/cli/VSOAgent_osx_3632209/AgentExtensions/vscode-install.sh"  ...
[2020-04-21 10:39:50.014 Agent.Workspace E] Failed to run VS Code Remote setup script: System.ComponentModel.Win32Exception (2): No such file or directory
```

I don't think that "No such file or directory" is coming from trying to execute this script, because nothing in bash-land is going to throw a "System.ComponentModel.Win32Exception". Presumably the script has run successfully, but has invoked something else (.net-ish?) that's then thrown this?

**Comment by taiyosogawa** [comment]
I think you're right about the Win32Exception - based on the code, I think it failed to find bash (even though you've verified that `which bash` can find it). It would fit in with your point that such an error wouldn't be thrown by bash itself. 

It looks like we don't have an absolute path to bash specified, so I am going to try changing that. Still haven't been able to repro it on my Macbook. Still thinking about this - just posting my current thoughts :)

**Comment by DanTup** [comment]
If there's anything you want me to try to help track it down, let me know (I'm happy to run dev builds of extensions if it helps). I'm mostly trying to get it working to do some testing of Dart/Flutter extensions that I work on (there's some interest in developing from Windows but building iOS apps which requires a Mac).

**Comment by taiyosogawa** [comment]
Hi @DanTup. Sorry, I missed your last message. In any case, I did notice the same issue happen on my Mac. I'm not exactly sure what changed but for some reason our agent was unable to invoke just `bash` even though `/bin` was included on the PATH. The change that I've deployed will explicitly invoke `/bin/bash` (if it is installed there) and it works for me. When you get a chance, try:

1) killing all running instances of `vso` and `vsls-agent` processes
2) If using the CLI `brew upgrade microsoft/vsonline/vso` and try vso start again
3) If youre using the extension simply try re-registering

**Comment by DanTup** [comment]
@taiyosogawa it all seems to work now, however the first time I connected to the MacBook environment (both from a browser or Windows) I saw this message:

![err](https://user-images.githubusercontent.com/1078012/81180277-b2797680-8fa2-11ea-8c2d-a76a83a15778.png)

After reloading, both then worked fine without any error.

Thanks!

**Comment by taiyosogawa** [comment]
Thanks @DanTup! I'm glad this issue was resolved. I'll see if anyone is tracking that toast issue.

**Comment by 2percentsilk** [comment]
Closing this issue due to lack of activity and the impending retirement of self-hosted on November 20, 2020.

As part of the [consolidation of VS Codespaces into GitHub](aka.ms/vscs-transition), self-hosted will need to be migrated to GitHub Codespaces but this migration isn't currently part of our roadmap.

If you have any thoughts/feedback on self-hosted Codespaces support in GitHub, please let us know by commenting on this [issue](https://github.community/t/self-hosted-codespaces/131361/19).
