### ISSUE TITLE
Self-hosted environment stuck in provisioning on Ubuntu

### ISSUE THREAD

**Issue by taiyosogawa** [MicrosoftDocs/vscodespaces#409]
Originally mentioned in #396

@onionhammer, I've got a few questions to help us diagnose the issue:
1) Are you running the self-hosted env as a process or as a service/daemon?
2) When it is trying to provision, do you see a `vso` or `vsls-agent` running?
3) Do you know if systemd is running on your machine? Does just running `systemctl` work? (It should print out a list of units).

**Comment by onionhammer** [comment]
Hi @taiyosogawa 

1. As a self-hosted service on Ubuntu (headless)
2. Yes, both vso and vsls-agent are running
3. Yes, systemctl works fine.

I was able to spin up a VM in azure and run vso start and add it without any issues, but on my home server it just sits at

"[2020-04-15 22:13:54.272 CLI I] Waiting for environment to become available..."

**Comment by taiyosogawa** [comment]
@onionhammer, thanks for the information - I think there's something here we haven't seen yet. 

When you run `vso start`, it will generate a `*_CLI` log and a `*.1_CLI` log under `/tmp/VSFeedbackVSRTCLogs` on the host Ubuntu machine. The former is more detailed than the latter, which is a copy of stdout. If you could, look for any errors/exceptions in the detailed '*_CLI' log and paste it here (omitting any personal details). 

If there are too many log files, I find it easier to remove them all from that directory then run again.

As for the 'already registered error': we're working on #406 to make restarting an existing environment easier, but at the moment running `vso stop` is the only way. Removing your `~/.vsonline` directory should also work.

**Comment by onionhammer** [comment]
@taiyosogawa Here's the latest *_CLI:

```
[2020-04-15 22:13:30.130 CLI I] vso v1.0.1998.63218 (pid: 13410)
[2020-04-15 22:13:30.289 CLI I] Cannot file environment variable file /home/erik/.vsonline/.vsoshared/environment-variables.json
[2020-04-15 22:13:30.290 CLI I] Attempting to read user settings from: /home/erik/.vs-liveshare-settings.json
[2020-04-15 22:13:30.342 CLI I] Performing Linux daemon manager checks...
[2020-04-15 22:13:30.342 CLI I] 	systemctl checked
[2020-04-15 22:13:30.342 CLI I] All Linux daemon manager checks passed
[2020-04-15 22:13:51.659 CLI I] Overriding serviceUri to https://prod.liveshare.vsengsaas.visualstudio.com/api/v1.2/
[2020-04-15 22:13:51.682 Client.Rpc V] => ProcessMessagesInternalAsync session #:1
[2020-04-15 22:13:51.727 Client.Rpc V] < #1 {Id=1 Name=version.exchangeVersions}
[2020-04-15 22:13:51.772 Client.Rpc V] > #1 {Id=1}
[2020-04-15 22:13:51.781 Client.Rpc V] < #1 {Id=2 Name=version.exchangeSettings}
[2020-04-15 22:13:51.789 Client.Rpc V] > #1 {Id=2}
[2020-04-15 22:13:51.792 Client.Rpc.Auth V] < #1 {Id=3 Name=auth.loginWithExternalToken}
[2020-04-15 22:13:51.828 Client.Rpc W] Service not available: auth
[2020-04-15 22:13:52.163 Client.Rpc W] Service not available: telemetry
[2020-04-15 22:13:52.195 Client.Rpc W] Service not available: auth
[2020-04-15 22:13:52.270 Client.Rpc.Auth V] > #1 {Id=3}
[2020-04-15 22:13:52.312 Client.Rpc I] RpcSession #1 is disposing.
[2020-04-15 22:13:52.317 Client.Rpc V] <= ProcessMessagesInternalAsync session #:1
[2020-04-15 22:13:52.319 Client.Rpc V] Emptying send queue of 0 messages.
[2020-04-15 22:13:52.319 Client.Rpc I] RpcSession #1 is disposing.
[2020-04-15 22:13:52.326 CLI I] Writing service file to /home/erik/.config/systemd/user/vso.service
[2020-04-15 22:13:52.327 CLI I] (0) Command: /bin/systemctl --user daemon-reload
[2020-04-15 22:13:52.332 CLI I] (0) [STDOUT]: 
[2020-04-15 22:13:52.332 CLI I] (0) [STDERR]: Failed to connect to bus: No such file or directory
[2020-04-15 22:13:52.332 CLI I] (0) [STDERR]: 
[2020-04-15 22:13:52.333 CLI I] (0) Exit code: 1
[2020-04-15 22:13:52.333 CLI I] (1) Command: /bin/systemctl --user start vso.service
[2020-04-15 22:13:52.335 CLI I] (1) [STDERR]: Failed to connect to bus: No such file or directory
[2020-04-15 22:13:52.335 CLI I] (1) [STDERR]: 
[2020-04-15 22:13:52.335 CLI I] (1) [STDOUT]: 
[2020-04-15 22:13:52.335 CLI I] (1) Exit code: 1
[2020-04-15 22:13:52.335 CLI I] (2) Command: /bin/systemctl --user enable vso.service
[2020-04-15 22:13:52.336 CLI I] (2) [STDERR]: Failed to connect to bus: No such file or directory
[2020-04-15 22:13:52.336 CLI I] (2) [STDOUT]: 
[2020-04-15 22:13:52.336 CLI I] (2) [STDERR]: 
[2020-04-15 22:13:52.337 CLI I] (2) Exit code: 1
[2020-04-15 22:13:54.268 CLI I] Skipping 'loginctl enable-linger' based on response 'n'
```

**Comment by onionhammer** [comment]
Another file had this:

```
[2020-04-14 18:47:52.469 CLI V] (2001) [Agent I] #1 Disconnected: Reached end of stream.
[2020-04-14 18:47:52.470 CLI V] (2001) [Agent I] RPC session #1 disconnected: Reached end of stream.
[2020-04-14 18:47:52.475 CLI V] (2001) [Agent V] Emptying send queue of 0 messages.
[2020-04-14 18:47:52.475 CLI V] (2001) [Agent-ObjectTracker V] Remove item:RpcSession #1 count:1 others:[KeepAliveAgent reason:AgentStarted delay:120000]
[2020-04-14 18:47:52.476 CLI V] (2001) [Agent I] RpcSession #1 is disposing.
[2020-04-14 18:47:52.480 CLI V] (2001) [Agent V] <= ProcessMessagesInternalAsync session #:1
```

**Comment by taiyosogawa** [comment]
Ah, thank you so much - this is very helpful. Based on the `Failed to connect to bus: No such file or directory` error, it looks like there may be some missing environment variables that are needed for running `systemctl --user` commands specifically. I'll try to repro this error.

We also recently made changes to make sure this type of error isn't swallowed - so `vso start` will actually fail instead of hang. Those changes should be available next week.

**Comment by onionhammer** [comment]
@taiyosogawa I wonder if it's related to disabling password based authentication (and using key pairs instead) on ubuntu?

In my sshd_config, I have UsePAM to no

**Comment by Niek** [comment]
I might have the same (or similar?) issue, here is my flow:
```bash
# vso start
[2020-04-17 08:43:08.116 CLI I] vso v1.0.1998.63218 (pid: 28518)
[2020-04-17 08:43:08.694 CLI I] Authenticating...
To sign in, use a web browser to open the page https://microsoft.com/devicelogin and enter the code CKDGP9ZJK to authenticate.
Would you like to run as a persistent service/daemon? [Y/n]: n
[2020-04-17 08:43:28.033 CLI I] Will run as a process
[2020-04-17 08:43:28.154 CLI I] A VSO plan is required to register your environment.
[2020-04-17 08:43:28.160 CLI I] Using VSO plan: /subscriptions/-snip-/resourceGroups/niek.my-server/providers/Microsoft.VSOnline/plans/vso-plan-westeurope
Enter an environment name or blank to use [niek]: niek.my
[2020-04-17 08:43:30.598 CLI I] Creating your environment...
[2020-04-17 08:43:32.092 CLI I] Saving local configurations...
[2020-04-17 08:43:32.186 CLI I] Authenticating...
[2020-04-17 08:43:36.071 CLI I] Waiting for environment to become available...
To log in, use a web browser to open the page:
    https://prod.liveshare.vsengsaas.visualstudio.com/auth/login
After logging in there, this prompt may auto-complete.
If not, copy and paste the resulting code below.

LOGIN CODE: To log in, use a web browser to open the page:
    https://prod.liveshare.vsengsaas.visualstudio.com/auth/login
After logging in there, this prompt may auto-complete.
If not, copy and paste the resulting code below.

LOGIN CODE: To log in, use a web browser to open the page:
    https://prod.liveshare.vsengsaas.visualstudio.com/auth/login
After logging in there, this prompt may auto-complete.
If not, copy and paste the resulting code below.

LOGIN CODE:
```
After this, the process hangs. Log files of CLI is full of this:

```bash
[2020-04-17 08:48:56.499 CLI I] Overriding serviceUri to https://prod.liveshare.vsengsaas.visualstudio.com/api/v1.2/
[2020-04-17 08:48:56.506 CLI V] (2001) [Agent I] Accepted incoming pipe connection.
[2020-04-17 08:48:56.509 CLI V] (2001) [Agent I] RPC session #8 established.
[2020-04-17 08:48:56.511 CLI V] (2001) [Agent-ObjectTracker V] Add item:RpcSession #8 count:2
[2020-04-17 08:48:56.521 Client.Rpc V] => ProcessMessagesInternalAsync session #:36
[2020-04-17 08:48:56.522 CLI V] (2001) [Agent V] => ProcessMessagesInternalAsync session #:8
[2020-04-17 08:48:56.532 Client.Rpc V] < #36 {Id=1 Name=version.exchangeVersions}
[2020-04-17 08:48:56.533 CLI V] (2001) [Agent V] > #8 {Id=1 Name=version.exchangeVersions Arguments=[null,{"extensionName":null,"extensionVersion":null,"applicationName":"vsonline-agent","applicationVersion":"1.0.1998","protocolVersion":null,"platformName":null,"platformVersion":null}]}
[2020-04-17 08:48:56.538 CLI V] (2001) [Agent V] < #8 {Result={VersionString=1.0.1998.63218 ProtocolVersionString=2.2 PlatformName=Linux 4.18.0 PlatformVersionString=4.18.0.25} Id=1}
[2020-04-17 08:48:56.541 Client.Rpc V] > #36 {Id=1}
[2020-04-17 08:48:56.541 Client.Rpc V] < #36 {Id=2 Name=version.exchangeSettings}
[2020-04-17 08:48:56.546 CLI V] (2001) [Agent V] > #8 {Id=2 Name=version.exchangeSettings Arguments=[{"agentAutoStart":true,"agentUri":"net.pipe://localhost/VSLS","serviceEndpoint":"https://prod.liveshare.vsengsaas.visualstudio.com/api/v1.2/","signalRServiceUri":"","isCloudEnvironment":true,"experimentalFeatures":{"propagateFolderEvents":false,"attemptReconnection":true},"increasedGuestLimit":true,"keychainFile":"/root/.vs-liveshare-keychain","syncRpcTelemetryTresholdMs":1000}]}
[2020-04-17 08:48:56.550 CLI V] (2001) [Agent V] < #8 {Result=<null> Id=2}
[2020-04-17 08:48:56.559 Client.Rpc V] > #36 {Id=2}
[2020-04-17 08:48:56.560 Client.Rpc.Workspace V] < #36 {Id=3 Name=workspace.listWorkspaces}
[2020-04-17 08:48:56.566 CLI V] (2001) [Agent.Rpc.Workspace V] > #8 {Id=3 Name=workspace.listWorkspaces Arguments=[{"includeRemoteWorkspaces":false}]}
[2020-04-17 08:48:56.570 CLI V] (2001) [Agent.Rpc.Workspace V] < #8 {Result={} Id=3}
[2020-04-17 08:48:56.580 Client.Rpc.Workspace V] > #36 {Id=3}
[2020-04-17 08:48:56.580 Client.Rpc I] RpcSession #36 is disposing.
[2020-04-17 08:48:56.584 Client.Rpc V] Emptying send queue of 0 messages.
[2020-04-17 08:48:56.585 Client.Rpc I] RpcSession #36 is disposing.
[2020-04-17 08:48:56.586 Client.Rpc V] <= ProcessMessagesInternalAsync session #:36
[2020-04-17 08:48:56.590 CLI V] (2001) [Agent I] #8 Disconnected: Reached end of stream.
[2020-04-17 08:48:56.592 CLI V] (2001) [Agent I] RPC session #8 disconnected: Reached end of stream.
[2020-04-17 08:48:56.593 CLI V] (2001) [Agent V] Emptying send queue of 0 messages.
[2020-04-17 08:48:56.594 CLI V] (2001) [Agent I] RpcSession #8 is disposing.
[2020-04-17 08:48:56.596 CLI V] (2001) [Agent V] <= ProcessMessagesInternalAsync session #:8
[2020-04-17 08:48:56.597 CLI V] (2001) [Agent-ObjectTracker V] Remove item:RpcSession #8 count:1 others:[KeepAliveAgent reason:AgentStarted delay:120000]
[2020-04-17 08:49:06.586 CLI I] Overriding serviceUri to https://prod.liveshare.vsengsaas.visualstudio.com/api/v1.2/
[2020-04-17 08:49:06.591 CLI V] (2001) [Agent I] Accepted incoming pipe connection.
[2020-04-17 08:49:06.594 CLI V] (2001) [Agent I] RPC session #9 established.
[2020-04-17 08:49:06.595 CLI V] (2001) [Agent-ObjectTracker V] Add item:RpcSession #9 count:2
[2020-04-17 08:49:06.600 Client.Rpc V] => ProcessMessagesInternalAsync session #:37
[2020-04-17 08:49:06.602 Client.Rpc V] < #37 {Id=1 Name=version.exchangeVersions}
[2020-04-17 08:49:06.608 CLI V] (2001) [Agent V] => ProcessMessagesInternalAsync session #:9
[2020-04-17 08:49:06.614 CLI V] (2001) [Agent V] > #9 {Id=1 Name=version.exchangeVersions Arguments=[null,{"extensionName":null,"extensionVersion":null,"applicationName":"vsonline-agent","applicationVersion":"1.0.1998","protocolVersion":null,"platformName":null,"platformVersion":null}]}
[2020-04-17 08:49:06.616 CLI V] (2001) [Agent V] < #9 {Result={VersionString=1.0.1998.63218 ProtocolVersionString=2.2 PlatformName=Linux 4.18.0 PlatformVersionString=4.18.0.25} Id=1}
[2020-04-17 08:49:06.620 Client.Rpc V] > #37 {Id=1}
[2020-04-17 08:49:06.621 Client.Rpc V] < #37 {Id=2 Name=version.exchangeSettings}
[2020-04-17 08:49:06.626 CLI V] (2001) [Agent V] > #9 {Id=2 Name=version.exchangeSettings Arguments=[{"agentAutoStart":true,"agentUri":"net.pipe://localhost/VSLS","serviceEndpoint":"https://prod.liveshare.vsengsaas.visualstudio.com/api/v1.2/","signalRServiceUri":"","isCloudEnvironment":true,"experimentalFeatures":{"propagateFolderEvents":false,"attemptReconnection":true},"increasedGuestLimit":true,"keychainFile":"/root/.vs-liveshare-keychain","syncRpcTelemetryTresholdMs":1000}]}
[2020-04-17 08:49:06.629 CLI V] (2001) [Agent V] < #9 {Result=<null> Id=2}
[2020-04-17 08:49:06.633 Client.Rpc V] > #37 {Id=2}
[2020-04-17 08:49:06.635 Client.Rpc.Workspace V] < #37 {Id=3 Name=workspace.listWorkspaces}
[2020-04-17 08:49:06.637 CLI V] (2001) [Agent.Rpc.Workspace V] > #9 {Id=3 Name=workspace.listWorkspaces Arguments=[{"includeRemoteWorkspaces":false}]}
[2020-04-17 08:49:06.641 CLI V] (2001) [Agent.Rpc.Workspace V] < #9 {Result={} Id=3}
[2020-04-17 08:49:06.644 Client.Rpc.Workspace V] > #37 {Id=3}
[2020-04-17 08:49:06.644 Client.Rpc I] RpcSession #37 is disposing.
[2020-04-17 08:49:06.647 Client.Rpc V] Emptying send queue of 0 messages.
[2020-04-17 08:49:06.648 Client.Rpc I] RpcSession #37 is disposing.
[2020-04-17 08:49:06.650 Client.Rpc V] <= ProcessMessagesInternalAsync session #:37
[2020-04-17 08:49:06.653 CLI V] (2001) [Agent I] #9 Disconnected: Reached end of stream.
[2020-04-17 08:49:06.655 CLI V] (2001) [Agent I] RPC session #9 disconnected: Reached end of stream.
[2020-04-17 08:49:06.657 CLI V] (2001) [Agent V] Emptying send queue of 0 messages.
[2020-04-17 08:49:06.659 CLI V] (2001) [Agent-ObjectTracker V] Remove item:RpcSession #9 count:1 others:[KeepAliveAgent reason:AgentStarted delay:120000]
```

**Comment by so5** [comment]
Hi, I have similar problem with my ubuntu server and Mac.

I got "Waiting for environment to become available..." and following message 1 hour later

```
[2020-04-17 09:03:31.593 CLI E] [!ERROR] Error calling HTTP GET at 'https://online.visualstudio.com/api/v1/environments/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx' ErrorCode : Unauthorized
```

On ubuntu server, I found the same systemctl 's error in  `/tmp/VSFeedbackVSRTCLogs/*CLI`.
But, I couldn't filnd any detailed log on Mac.

@taiyosogawa,  could you tell me which files should I check on Mac?

**Comment by taiyosogawa** [comment]
Thank you all for your patience and I'm sorry if this is too late.

@onionhammer, the changes to print better error messaging could be out. Could you try again to see if it prints any better information? You could also just try running `/bin/systemctl --user daemon-reload` to see if that works.

@Niek, it looks like it's failing to find the access token cached during setup. Have you used Codespaces or Liveshare with a different email by any chance? Do you see a `~/.vs-liveshare-keychain` file? Do the contents show multiple email addresses?

@so5, try $TMPDIR/VSFeedbackVSRTCLogs

**Comment by onionhammer** [comment]
@taiyosogawa as far as I can tell, same behavior as before.

**Comment by taiyosogawa** [comment]
@onionhammer, ah I see. I tried setting my UsePAM to no, too, but wasn't able to repro.

There is something going on with the systemctl, but it is peculiar that it works when you run it. Do you see the environment variable `XDG_RUNTIME_DIR` set?  I'm looking at [this post](https://answers.launchpad.net/ubuntu/+source/systemd/+question/287454)

**Comment by onionhammer** [comment]
@taiyosogawa Yes, it's set to this:

XDG_SESSION_ID=c1
XDG_RUNTIME_DIR=/run/user/0

**Comment by so5** [comment]
@taiyosogawa I check the CLI log file under  `$TMPDIR/VSFeedbackVSRTCLogs` but I can not find any error message.

I also try to reproduce on my mac, but successfully finished `vso start` this time.
I'm not sure what happened but please don't worry about mac.

**Comment by taiyosogawa** [comment]
@onionhammer, thank you so much for your patience and help so far. Could you try setting XDG_RUNTIME_DIR to `/run/user/<ID>`? (run `id` and use the numerical uid value for `<ID>`)? If you're able to register, we can update our CLI to check that environment variable.

@so5, thank you for reporting and trying again. Please report any additional issues you encounter.

**Comment by onionhammer** [comment]
@taiyosogawa 

after setting $XDG_RUNTIME_DIR to `/run/user/1000` and trying again I get the same result; console sits there and online.visualstudio.com/envronments says "creating" (for however long it takes to timeout)

**Comment by mschickervxob** [comment]
Could be this: https://github.com/MicrosoftDocs/vsonline/issues/453

**Comment by DAddYE** [comment]
I confirm that after:

1. Deregistering from vscode all the codespaces
2. `kill -9` all the pids in`ps aux | grep vso`

I was able to register a new codespace without problems, while before I was getting as well Unauthorized.

**Comment by DAddYE** [comment]
> Thank you all for your patience and I'm sorry if this is too late.
> 
> @onionhammer, the changes to print better error messaging could be out. Could you try again to see if it prints any better information? You could also just try running `/bin/systemctl --user daemon-reload` to see if that works.
> 
> @Niek, it looks like it's failing to find the access token cached during setup. Have you used Codespaces or Liveshare with a different email by any chance? Do you see a `~/.vs-liveshare-keychain` file? Do the contents show multiple email addresses?
> 
> @so5, try $TMPDIR/VSFeedbackVSRTCLogs

Hi, seems that even if now I'm able to register the codespace, I'm unable to bootstrap it, and the issue seems related to auth. 

```
[2020-07-02 20:56:58.948 Client.Rpc.Workspace V] > #161 {Id=4 Error={Code=-32032 Message=Your sign in token has expired. Please sign out and in again to refresh it. If the issue persists, please log a bug. Data=(StackTrace=   at Microsoft.Cascade.Agent.HttpResponseMessageExtensions.ThrowHttpStatusException(HttpResponseMessage response) in E:\A\_work\510\s\src\Agent\HttpResponseMessageExtensions.cs:line 90
   at Microsoft.Cascade.Agent.HttpResponseMessageExtensions.ThrowIfFailedAsync(HttpResponseMessage response) in E:\A\_work\510\s\src\Agent\HttpResponseMessageExtensions.cs:line 48
   at Microsoft.Cascade.Agent.WebApiCollection`1.ReadAsync(String id, CancellationToken cancellationToken) in E:\A\_work\510\s\src\Agent\WebApiCollection.cs:line 76
   at Microsoft.Cascade.Agent.WorkspaceService.GetInvitationLinksAsync(String workspaceId, CancellationToken cancellationToken) in E:\A\_work\510\s\src\Agent\WorkspaceService.cs:line 1282
   at Microsoft.Cascade.Rpc.RpcDispatcher`1.<>c__DisplayClass24_2.<<CreateDispatchMethod>b__4>d.MoveNext() in E:\A\_work\510\s\src\Rpc\RpcDispatcher.cs:line 311
```

Thank you!

**Comment by 2percentsilk** [comment]
Hi everyone,

It looks like most issues were solved in this issue outside of the bootstrapping of the self-hosted machine. @DAddYE is the bootstrapping issue still happening?

To set expectations moving forward, the self-hosted service is being retired on November 20, 2020 as part of the [Visual Studio Codespaces transition to GitHub Codespaces](aka.ms/vscs-transition]. Self-hosted support is not currently included in the GitHub roadmap so the team is prioritizing work elsewhere in the service. We will do their best to assist but we cannot guarantee a speedy response. You can join the conversation about the future of self-hosted over at [GitHub Community](https://github.community/t/self-hosted-codespaces/131361/24).

Thanks for participating in our preview and providing feedback!

**Comment by taiyosogawa** [comment]
Closing as self-hosted has been retired.
