### ISSUE TITLE
Refused to execute script because its MIME type ('text/html') is not executable

### ISSUE THREAD

**Issue by bpasero** [MicrosoftDocs/vscodespaces#436]
In devtools:

```
Refused to execute script from 'https://online.visualstudio.com/workbench-page/web-standalone/insider-0778354/node_modules/xterm/lib/xterm.js-addon-unicode11.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.
log.ts:197   ERR [object Event]: Error: [object Event]
    at Object.t [as ensureError] (https://online.visualstudio.com/workbench-page/web-standalone/insider-0778354/out/vs/loader.js:7:522)
    at s._createLoadError (https://online.visualstudio.com/workbench-page/web-standalone/insider-0778354/out/vs/loader.js:27:162)
    at s._onLoadError (https://online.visualstudio.com/workbench-page/web-standalone/insider-0778354/out/vs/loader.js:27:281)
    at i (https://online.visualstudio.com/workbench-page/web-standalone/insider-0778354/out/vs/loader.js:29:20)
    at Object.errorback (https://online.visualstudio.com/workbench-page/web-standalone/insider-0778354/out/vs/loader.js:29:383)
    at e.triggerErrorback (https://online.visualstudio.com/workbench-page/web-standalone/insider-0778354/out/vs/loader.js:13:955)
    at https://online.visualstudio.com/workbench-page/web-standalone/insider-0778354/out/vs/loader.js:13:659
    at HTMLScriptElement.i (https://online.visualstudio.com/workbench-page/web-standalone/insider-0778354/out/vs/loader.js:14:176)
```

**Comment by lostintangent** [comment]
Closing this since we're tracking it in another repo, and we don't need it duplicated here (since we're slowly phasing out this repo). Thanks!
