### ISSUE TITLE
VS Code Server failed to start with ENOTCONN

### ISSUE THREAD

**Issue by seanpk** [MicrosoftDocs/vscodespaces#641]
I was just trying to use VS Code to connect to a remote server (for the first time) to edit some scripts.

I get this error: `> Server did not start successfully. Full server log at /home/jewjrwif/.vscodeserver/.cd9ea6488829f560dc949a8b2fb789f3cdc05f5d.log >>>`

Here's the log:
```

*
* Visual Studio Code Server
*
* Reminder: You may only use this software with Visual Studio family products,
* as described in the license https://aka.ms/vscode-remote/license
*


events.js:177
      throw er; // Unhandled 'error' event
      ^

Error: read ENOTCONN
    at Socket._read (net.js:528:20)
    at Socket.Readable.read (_stream_readable.js:474:10)
    at new Socket (net.js:328:12)
    at Object.Socket (net.js:237:41)
    at createSocket (internal/child_process.js:311:14)
    at ChildProcess.spawn (internal/child_process.js:424:23)
    at spawn (child_process.js:535:9)
    at Object.execFile (child_process.js:217:17)
    at Object.exec (child_process.js:145:25)
    at /home/jewjrwif/.vscode-server/bin/cd9ea6488829f560dc949a8b2fb789f3cdc05f5d/out/vs/server/remoteExtensionHostAgent.js:141:938
    at new Promise (<anonymous>)
    at /home/jewjrwif/.vscode-server/bin/cd9ea6488829f560dc949a8b2fb789f3cdc05f5d/out/vs/server/remoteExtensionHostAgent.js:141:912
    at new Promise (<anonymous>)
    at Object.t.getMac (/home/jewjrwif/.vscode-server/bin/cd9ea6488829f560dc949a8b2fb789f3cdc05f5d/out/vs/server/remoteExtensionHostAgent.js:141:791)
    at /home/jewjrwif/.vscode-server/bin/cd9ea6488829f560dc949a8b2fb789f3cdc05f5d/out/vs/server/remoteExtensionHostAgent.js:143:741
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
    at async /home/jewjrwif/.vscode-server/bin/cd9ea6488829f560dc949a8b2fb789f3cdc05f5d/out/vs/server/remoteExtensionHostAgent.js:143:650
Emitted 'error' event at:
    at emitErrorNT (internal/streams/destroy.js:91:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:9) {
  errno: 'ENOTCONN',
  code: 'ENOTCONN',
  syscall: 'read'
}
```

In VS Code I also see these messages after the server log dump:
```
> 59d439b21052##32##
[10:44:20.551] Received install output: 59d439b21052##32##
[10:44:20.552] Terminating local server
[10:44:20.555] Resolver error: The VS Code Server failed to start
[10:44:20.564] Local server exit: 15
[10:44:20.569] ------
```

**Comment by lostintangent** [comment]
@seanpk Just to confirm: were you using Codespaces? Or was this error something you encountered when using VS Code's support for SSH?

@jkeech Thoughts here? This is the time I've seen this issue reported, so maybe it's since been resolved?

**Comment by jkeech** [comment]
This doesn't look like Codespaces to me, so I'm going to go ahead and close the issue. Please re-open if we are misunderstanding. Thanks!
