### ISSUE TITLE
Unable to open Github codespace

### ISSUE THREAD

**Issue by david-driscoll** [MicrosoftDocs/vscodespaces#673]
Hi I'm currently unable to connect to a github codespace using vscode (in this case code insiders).

I am able to connect to Microsoft based code spaces without issue, this is strictly related to Github Codespaces (and I think it's because I've authenticated with the Microsoft codespaces, but I'm not 100% certain)

The logs I'm getting are:
```
[Client V] Initializing authentication
[Client I] Trace log: <path>
[Client V] Initializing self-hosted environment registry
[Client I] Extension activating {"isInternal":false,"isRunningInCloudEnvironment":false,"serviceEndpoint":"https://online.visualstudio.com/api/v1/environments"}
[EnvironmentDetailsExplorer I] Updating environment details
[VSOnlineResolver I] Resolving vsonline: <guid>
[VSOnlineResolver I] Fetching codespace details
[EnvironmentInfo E] Failed to fetch environments
Fetch codespace list request failed with status 404
Error: Fetch codespace list request failed with status 404
    at t.GitHubApi.listCodespaces (...\extenisons\ms-vsonline.vsonline-1.0.2526\src\partners\github\githubApi.ts:38:15)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at t.GitHubEnvironmentsApi.getEnvironmentList (...\extenisons\ms-vsonline.vsonline-1.0.2526\src\partners\github\githubEnvironmentsApi.ts:45:15)
    at updateEnvironmentsInfo (...\extenisons\ms-vsonline.vsonline-1.0.2526\src\EnvironmentInfo.ts:55:13)
[Client E] Failed to update environments list: Fetch codespace list request failed with status 404
Fetch codespace list request failed with status 404
Error: Fetch codespace list request failed with status 404
    at t.GitHubApi.listCodespaces (...\extenisons\ms-vsonline.vsonline-1.0.2526\src\partners\github\githubApi.ts:38:15)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at t.GitHubEnvironmentsApi.getEnvironmentList (...\extenisons\ms-vsonline.vsonline-1.0.2526\src\partners\github\githubEnvironmentsApi.ts:45:15)
    at t.EnvironmentExplorer.updateInitializationStatus (...\extenisons\ms-vsonline.vsonline-1.0.2526\src\treeView\EnvironmentExplorer.ts:80:22)
[VSOnlineResolver E] Resolve failed: Error: Fetch codespace list request failed with status 404
[Client I] User logged in as email@email.com
[Client I] User logged in as email@email.com
```

An additional error message:

```
Unable to open 'FluentValidation': Unable to read file 'vscode-remote://vsonline+<guid>/home/codespace/workspace/FluentValidation' (Error: Fetch codespace list request failed with status 404).
```

Let me know if you need any more details.

Thanks!

**Comment by jkeech** [comment]
@david-driscoll, we pushed a new extension version today which fixes an auth issue with the GitHub flows. Can you see if updating fixes your problem? cc @cmbrose

**Comment by david-driscoll** [comment]
@jkeech unfortunately still seems to be an issue.

**Comment by jkeech** [comment]
Thanks for checking! We are looking into it.

**Comment by cmbrose** [comment]
@david-driscoll I have a suspicion about what is going on here - do you have any other extension installed which used GitHub authentication (the GitHub PR extension for example)?  If so, is it possible that you have signed into different GitHub accounts with that extension and the Codespaces extension?

Additionally, some general questions to help narrow it down:
- Are you able to use GitHub codespaces in the browser with no issue?
- In desktop, are you able to list codespaces outside of the connection context? (i.e. you can see the list of Codespaces which you can connect to)
- What OS are you on?

**Comment by lostintangent** [comment]
Closing this issue due to inactivity, and the fact that we've completely re-worked the VS Code client extension as part of consolidating Codespaces into GitHub Codespaces. Please re-open this if you're still running into issues. Thanks!
