### ISSUE TITLE
Self hosting on centos 7 as service not working

### ISSUE THREAD

**Issue by shorman88** [MicrosoftDocs/vscodespaces#749]
Hello,

I followed this [guide ](https://docs.microsoft.com/en-us/visualstudio/codespaces/reference/vsonline-cli) to install self-hosted codespaces on Centos 7 everything is fine but i can't run it as service, please check the below error:

```
 [2020-08-17 16:22:15.682 CLI I] Authenticating...

[2020-08-17 16:22:19.535 CLI I] Creating your Codespace...

[2020-08-17 16:22:21.843 CLI I] Authenticating...

[2020-08-17 16:22:24.277 CLI I] Saving local configurations...

[2020-08-17 16:22:24.640 CLI I] Starting agent...

[2020-08-17 16:22:24.642 CLI I] Creating service...

[CLI E] Failed to run: systemctl {command}

[2020-08-17 16:22:24.660 CLI E] [!ERROR] Failed to register and start service/daemon: System.Exception: unable to run /bin/systemctl --user daemon-reload
   at Microsoft.VisualStudio.VSOnline.Core.Platforms.Linux.LinuxDaemonManager.RunSystemCtl(String[] arguments) in E:\A\_work\559\s\src\VSOnline\Core\Platforms\Linux\LinuxDaemonManager.cs:line 206
   at Microsoft.VisualStudio.VSOnline.Core.Platforms.Linux.LinuxDaemonManager.CreateServiceAsync(String user) in E:\A\_work\559\s\src\VSOnline\Core\Platforms\Linux\LinuxDaemonManager.cs:line 72
   at Microsoft.CloudEnvironments.CLI.Commands.StartSelfHostedCommand.StartVmAgentServiceAsync(String user) in E:\A\_work\559\s\src\VSOnline\CLI\Commands\StartSelfHostedCommand.cs:line 234
   at Microsoft.CloudEnvironments.CLI.Commands.StartSelfHostedCommand.ExecuteAsync(StartSelfHostedParams parameters, String aadToken) in E:\A\_work\559\s\src\VSOnline\CLI\Commands\StartSelfHostedCommand.cs:line 193

```
I tried with root and with a standard user and i got the same error.

please check the below output of two commands
```
[root@host ~]# systemctl --user daemon-reload
Failed to get D-Bus connection: No such file or directory
[root@host ~]# systemctl daemon-reload
```

Did i miss anything?

**Comment by taiyosogawa** [comment]
Centos 7 is not explicitly supported at the moment, and @shorman88 , I think you have correctly identified the issue. We interact with systemd with the `--user` flag to avoid the necessity to run as a sudoer, but it looks like systemd does not support that here. Unfortunately I'm afraid only the process option will be available until we create support for this scenario.

**Comment by shorman88** [comment]
Thanks @taiyosogawa, is there a way to have the process option work again? I mean if the process got killed or the server got restarted, how can i re-authenticate again?
