### ISSUE TITLE
Self-hosted codespace can't use settings sync

### ISSUE THREAD

**Issue by haberdashPI** [MicrosoftDocs/vscodespaces#767]
I have setup a self-hosted codespace on a local machine. That machine is running Ubuntu 20.04. When I log into that machine on my Mac in Chrome, via online.visualstudio.com and try to turn on settings sync I get an error:

```log
[2020-08-25 13:32:03.210] [window] [error] Unable to resolve non-existing file 'vscode-userdata:/User/sync/54759f/settings/preview/settings.json': Error: Unable to resolve non-existing file 'vscode-userdata:/User/sync/54759f/settings/preview/settings.json'
    at b.resolve (https://online.visualstudio.com/workbench-page/web-standalone/stable-3dd9051/out/vs/workbench/workbench.web.api.js:1649:765)
    at async b.doGenerateSyncResourcePreview (https://online.visualstudio.com/workbench-page/web-standalone/stable-3dd9051/out/vs/workbench/workbench.web.api.js:2788:2)
[2020-08-25 13:33:35.070] [window] [error] [object Event]: Error: [object Event]
    at Object.t [as ensureError] (https://online.visualstudio.com/workbench-page/web-standalone/stable-3dd9051/out/vs/loader.js:7:572)
    at s._createLoadError (https://online.visualstudio.com/workbench-page/web-standalone/stable-3dd9051/out/vs/loader.js:27:749)
    at s._onLoadError (https://online.visualstudio.com/workbench-page/web-standalone/stable-3dd9051/out/vs/loader.js:27:868)
    at i (https://online.visualstudio.com/workbench-page/web-standalone/stable-3dd9051/out/vs/loader.js:29:600)
    at Object.errorback (https://online.visualstudio.com/workbench-page/web-standalone/stable-3dd9051/out/vs/loader.js:29:963)
    at e.triggerErrorback (https://online.visualstudio.com/workbench-page/web-standalone/stable-3dd9051/out/vs/loader.js:14:306)
    at https://online.visualstudio.com/workbench-page/web-standalone/stable-3dd9051/out/vs/loader.js:14:10
    at HTMLScriptElement.i (https://online.visualstudio.com/workbench-page/web-standalone/stable-3dd9051/out/vs/loader.js:14:527)
```

I assume it is trying to find this file on the Ubuntu machine, which obviously doesn't have a folder called `/User` (looks more like a mac directory (but that is normally called `/Users`).

**Comment by khkh-ms** [comment]
I am sorry that you are having the issue with the settings sync in your Codespace. We are looking into it. Could you please share the ID of the Codespace you are having the issue with?

**Comment by haberdashPI** [comment]
Thanks for your reply; can you tell me where I would find the id? Is that the string at the end of the `online.visuablstudio.com` url? If so, that's `7bcf31bc-7353-4fb6-b776-2756df1280df`

**Comment by smvanderweide** [comment]
Yes, that is the id we needed, thanks!

**Comment by isair** [comment]
I've had the same issue since the sync feature was first introduced.

**Comment by haberdashPI** [comment]
The id has changed because something crashed. It is now e1f7c5fb-9592-4f4f-a139-c61ec2c5c807
