### ISSUE TITLE
Cannot connect with VSCode to Codespace created with Visual Studio

### ISSUE THREAD

**Issue by lukka** [MicrosoftDocs/vscodespaces#836]
VS Codespace: v1.0.3075

Version: 1.52.0-insider (user setup)
Commit: a36c68b9ec3d6a0aca9799d7a10be741a6658a51
Date: 2020-11-19T05:37:52.577Z
Electron: 9.3.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19042

The user experience is a message "cannot find the file", without mentioning which file, and why that file is being searched for.
![image](https://user-images.githubusercontent.com/681992/99701919-f9fcb700-2a49-11eb-9c31-c54eaa5c9b17.png)

Content of Log(Window)

```
[2020-11-19 09:24:01.148] [renderer1] [error] Unable to read file 'vscode-remote://vsonline+4344dedc-2114-4c56-abd2-c7d7fdf98568+accountprovider=github/c:/workspace/.vscode/launch.json' (Error: The system cannot find the file specified.): Error: Unable to read file 'vscode-remote://vsonline+4344dedc-2114-4c56-abd2-c7d7fdf98568+accountprovider=github/c:/workspace/.vscode/launch.json' (Error: The system cannot find the file specified.)
    at _.doReadAsFileStream (file:///C:/Users/lucappa/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1790:809)
    at async _.readFile (file:///C:/Users/lucappa/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:1789:933)
    at async file:///C:/Users/lucappa/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:3714:162
    at async Promise.all (index 1)
    at async Promise.all (index 1)
    at async m.loadConfiguration (file:///C:/Users/lucappa/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:3714:322)
    at async Promise.all (index 0)

```

**Comment by jekelly** [comment]
Similar problem from GH.com, although error is slightly different:

![image](https://user-images.githubusercontent.com/9146472/99718437-b44ae900-2a5f-11eb-8391-bc8d581e7675.png)

[2020-11-19 12:07:04.846] [window] [error] The event "start.block: TimeToFirstConnection-end" already marked in this group.: Error: The event "start.block: TimeToFirstConnection-end" already marked in this group.
    at o.markBlock (https://jekelly-ninja-rgqm.github.dev/static/js/workbench.a46fe75b.chunk.js:1:81749)
    at o.markBlockEnd (https://jekelly-ninja-rgqm.github.dev/static/js/workbench.a46fe75b.chunk.js:1:82135)
    at a.markBlockEnd (https://jekelly-ninja-rgqm.github.dev/static/js/workbench.a46fe75b.chunk.js:1:83741)
    at https://jekelly-ninja-rgqm.github.dev/static/js/workbench.a46fe75b.chunk.js:35:84330
    at o.measure (https://jekelly-ninja-rgqm.github.dev/static/js/workbench.a46fe75b.chunk.js:1:82376)
    at a.measure (https://jekelly-ninja-rgqm.github.dev/static/js/workbench.a46fe75b.chunk.js:1:83836)
    at $.initializeChannel (https://jekelly-ninja-rgqm.github.dev/static/js/workbench.a46fe75b.chunk.js:35:83991)

@jkeech

**Comment by dgurns** [comment]
Same error here as @jekelly:

```
Failed to connect to the remote extension host server (Error: The event "start.block: TimeToFirstConnection-end" already marked in this group.)
```

Everything was working fine, then the terminal hung and now when I reopen the codespace, the VSCode chrome is navigable, but it won’t actually connect to the files.
