### ISSUE TITLE
Unable to connect to self-hosted environment: Failed to connect to relay

### ISSUE THREAD

**Issue by wazybr** [MicrosoftDocs/vscodespaces#88]
After registering a local environment and trying to connect to it via the web-based editor, the connection doesn't succeed and the editor's console keeps getting spammed with the following error:

```
[2019-11-05 21:52:11.648] [window] [error] Failed to connect to relay: wss://vsls-prod-ins-use-private-relay.servicebus.windows.net:443/$hc/####################################--########-####-####-####-############?sb-hc-action=connect&sb-hc-token=SharedAccessSignature%20sr%3Dsb%253A%252F%252Fvsls-prod-ins-use-private-relay.servicebus.windows.net%####################################--########-####-####-####-############%26sig%3DB%252Bro%25###################%25######################%253D%26se%3D##########%26skn%3DWorkspaceShareKey: Error: Failed to connect to relay: wss://vsls-prod-ins-use-private-relay.servicebus.windows.net:443/$hc/####################################--########-####-####-####-############?sb-hc-action=connect&sb-hc-token=SharedAccessSignature%20sr%3Dsb%253A%252F%252Fvsls-prod-ins-use-private-relay.servicebus.windows.net%25####################################--########-####-####-####-############%26sig%3DB%252Bro%25###################%25######################%253D%26se%3D##########%26skn%3DWorkspaceShareKey
    at WebSocket.n.onerror (https://online.visualstudio.com/static/js/main.275e0a1c.chunk.js:1:128082)
```

The issue is occurring on a personal Windows 10 laptop. Restoring the environment doesn't work, generating an authentication error:

```
[Command:RestoreLocalEnvironment E] Command [Unabled to restore local environment]: Restore local environment Failure: Unable to authenticate (3892ms)
```

Tried unregistering and re-registering multiple times to no avail. Still unable to connect.

**Comment by josh-greenlaw** [comment]
I can get it working for a very short amount of time, but only when I access the environment (via web browser) from the same machine that it is hosted on. If I leave the environment idle for a while or try connecting from a remote machine, I get the same error.

**Comment by wazybr** [comment]
My attempts were through the web-based editor from the same machine.

**Comment by jkeech** [comment]
@wazybr, are you still experiencing this issue with the latest version of the extension?

**Comment by wazybr** [comment]
I was trying to check it right now. When downloading dependencies to register the environment, my internet connection got down and then the registration failed. Now, every time I try to register again, it fails with this error:

`Register Self-hosted Environment: (Error 1) 'C:\Users\<Username>\.vsonline\cli\VSOAgent_win_3612700\vso' is not recognized as an internal or external command, operable program or batch file.`

Reinstalling the extension and restart VSCode doesn't solve. Will check if there's already an issue for that later.

**Comment by taiyosogawa** [comment]
@wazybr, sorry about that - we have an open item for repairing failed downloads. In the meantime, try deleting the `C:\Users\<username>\.vsonline` folder and trying again. Restart/extension update won't be required, but good thinking :)

**Comment by wazybr** [comment]
Thank you. I thought reinstalling the extension would delete all files related to it (maybe this should be discussed).

Anyway, it's now stuck in "Registering environment: \<environment\>". Here's the log:

```
[StaticEnvironmentRegistration I] vso: [2020-04-09 23:00:14.786 CLI I] Using VSO URI: https://online.visualstudio.com/api/v1/
[StaticEnvironmentRegistration I] vso: [2020-04-09 23:00:17.978 CLI I] Creating your environment...
[StaticEnvironmentRegistration I] vso: [2020-04-09 23:00:20.820 CLI I] Saving local configurations...
[StaticEnvironmentRegistration I] vso: [2020-04-09 23:00:22.139 CLI I] Authenticating...
[StaticEnvironmentRegistration I] vso: [2020-04-09 23:00:29.268 CLI I] Waiting for environment to become available...
```

**Comment by taiyosogawa** [comment]
I see it's failing to flip to available. I've created a separate issue #396 to track so that others can find it more easily.

**Comment by wazybr** [comment]
After being able to successfully register my self-hosted environment, I'm still unable to connect to it. It's failing with this error:
![image](https://user-images.githubusercontent.com/49368302/79033737-04d39d00-7b87-11ea-8afb-190521641b15.png)

The clients' log shows this:
```
ERR [remote-connection] The time limit has been reached for a connection. Error:
log.ts:197   ERR Error: Time limit reached
    at remoteAgentConnection.ts:523
log.ts:197   ERR [remote-connection] An error occurred in the very first connect attempt, it will be treated as a permanent error! Error:
```
And after that, it keeps getting spammed with:
```
ERR An unknown error occurred. Please consult the log for more details.: Error
```

Still, the workbench is able to show my workspace's name, but nothing more. See:
![image](https://user-images.githubusercontent.com/49368302/79033842-e1f5b880-7b87-11ea-9581-a747de662125.png)

**Comment by maswitzer** [comment]
I'm getting this same error when trying to run a self-hosted environment as a service with vso start --service. Everything seems like it's working fine during the setup processes, but once I try to connect to the environment I'm receiving the same "Failed to connect to relay" error in the browser (if I'm even able to get to it) and my VS Codespaces environments page shows it as Unavailable.

This only happens when trying to run it as a service though. Running it as a temporary process works just fine. I pulled this log from /tmp/vsonline_logs if this is of any help:

This is on Ubuntu Server 20.04 running vso v1.0.2368.34261 CLI.

```
[2020-06-22 00:43:55.804 Client V] Initializing authentication
[2020-06-22 00:43:56.180 Client V] Initializing self-hosted environment registry
[2020-06-22 00:43:56.182 Client I] Extension activating {"isInternal":false,"isRunningInCloudEnvironment":true,"serviceEndpoint":"https://online.visualstudio.com/api/v1/environments","environmentId":"7765e91a-b450-45a2-b275-1d759a1cf446"}
[2020-06-22 00:43:56.183 EnvironmentDetailsExplorer I] Updating environment details
[2020-06-22 00:43:56.309 Client I] User logged in as <user>
[2020-06-22 00:43:56.413 EnvironmentDetailsExplorer I] Updating environment details
[2020-06-22 00:43:56.538 EnvironmentDetailsExplorer I] Updating environment details
[2020-06-22 00:43:56.675 Client I] Connecting to current environment: 7765e91a-b450-45a2-b275-1d759a1cf446
[2020-06-22 00:43:56.676 Command:b I] Decorator starting: l
[2020-06-22 00:43:56.676 Command:b I] Decorator starting: a
[2020-06-22 00:43:56.676 Connect I] Connecting to environment: {"environmentId":"7765e91a-b450-45a2-b275-1d759a1cf446","isRunningInCloudEnvironment":true,"initialConnectionToCurrentEnvironment":true,"hasResolver":true}
[2020-06-22 00:43:56.680 Connect V] Connecting extension to current environment.
[2020-06-22 00:43:56.681 EnvironmentDetailsExplorer I] Updating environment details
[2020-06-22 00:43:56.682 WorkspaceApi V] get workspace info -> https://prod.liveshare.vsengsaas.visualstudio.com/api/v1.2/workspace/C5729E5C2677274E1F5F404B65D15CA503AF
[2020-06-22 00:43:56.682 FetchRequest:1 V] GET - fetch start
[2020-06-22 00:43:56.892 FetchRequest:1 V] GET - fetch response. (url=https://prod.liveshare.vsengsaas.visualstudio.com/api/v1.2/workspace/C5729E5C2677274E1F5F404B65D15CA503AF;status=200)
[2020-06-22 00:43:56.893 WorkspaceApi V] get workspace access -> https://prod.liveshare.vsengsaas.visualstudio.com/api/v1.2/workspace/9AF75D965A5EE26693D459B9E904552585FE/user
[2020-06-22 00:43:56.893 FetchRequest:2 V] PUT - fetch start
[2020-06-22 00:43:57.469 FetchRequest:2 V] PUT - fetch response. (url=https://prod.liveshare.vsengsaas.visualstudio.com/api/v1.2/workspace/9AF75D965A5EE26693D459B9E904552585FE/user;status=200)
[2020-06-22 00:43:57.470 WorkspaceClient V] connecting to relay link:sb://vsls-prod-ins-use-private-relay.servicebus.windows.net/9af75d965a5ee26693d459b9e904552585fe--d0ba32b4-2c8b-4dc8-8fb2-132e8349d7b0
[2020-06-22 00:43:57.470 WorkspaceClient V] creating node SSH...
[2020-06-22 00:43:57.647 WorkspaceClient V] authenticating...
[2020-06-22 00:43:57.736 WorkspaceClient V] joining...
[2020-06-22 00:43:57.760 WorkspaceClient V] < version.exchangeVersions()
[2020-06-22 00:43:57.767 WorkspaceClient V] > version.exchangeVersions() succeeded t:7.0
[2020-06-22 00:43:57.767 WorkspaceClient I] Host version: {"version":"1.0.2368.34261","protocolVersion":"2.2","platformName":"Linux 5.4.0","platformVersion":"5.4.0.1016"}
[2020-06-22 00:43:57.767 WorkspaceClient V] < workspace.joinWorkspace()
[2020-06-22 00:43:57.774 WorkspaceClient E] > workspace.joinWorkspace() error: undefined
[2020-06-22 00:43:58.593 WorkspaceServices E] Exception joining workspace C5729E5C2677274E1F5F404B65D15CA503AF
Sequence contains more than one matching element
Error: Sequence contains more than one matching element
    at handleResponse (/home/<user>/.vscode-remote/extensions/node_modules/vscode-jsonrpc/lib/main.js:436:48)
    at processMessageQueue (/home/<user>/.vscode-remote/extensions/node_modules/vscode-jsonrpc/lib/main.js:263:17)
    at Immediate.<anonymous> (/home/<user>/.vscode-remote/extensions/node_modules/vscode-jsonrpc/lib/main.js:247:13)
    at processImmediate (internal/timers.js:439:21)
[2020-06-22 00:46:19.998 WorkspaceClient V] connecting to relay link:sb://vsls-prod-ins-use-private-relay.servicebus.windows.net/9af75d965a5ee26693d459b9e904552585fe--d0ba32b4-2c8b-4dc8-8fb2-132e8349d7b0
[2020-06-22 00:46:19.999 WorkspaceClient V] creating node SSH...
[2020-06-22 00:46:20.102 WorkspaceClient V] failed to reconnect ssh session retryCount:1 error:Error: The relay endpoint for the environment is invalid or no longer exists.
```

**Comment by wazybr** [comment]
I was still having the issue. Opening VSCode as administrator and running the self-hosted env as a service worked for me (didn't have time to check which one of those steps made it work).

**Comment by 2percentsilk** [comment]
Hi there,

Apologies for the delayed response - I'm glad to see some workarounds were reached.

Given [Codespaces is transitioning to GitHub](https://devblogs.microsoft.com/visualstudio/visual-studio-codespaces-is-consolidating-into-github-codespaces/) and self-hosted support will be retired on November 20, 2020, I'm going to close down this issue as won't fix since we won't be investing in improving this feature set further.

If you have any thoughts/feedback on self-hosted Codespaces support in GitHub, please let us know by commenting on this [issue](https://github.community/t/self-hosted-codespaces/131361/19).
